## Attachment

+ filename: `attachment.jpg` (string, required) - Name of the attached file
+ url: `http://example.com/attachment.jpg` (string, required) - URL to download the attached file
+ content_type: `image/jpeg` (string, required) - Content type of the attached file
+ size: `10000` (number, required) - Size (in byte) of the attached file
