## Channel

<!-- include(../includes/links_attribute.apib) -->
    + self: `https://api2.frontapp.com/channels/cha_55c8c149` (string, required) - URL of the channel.
    + related (object, required)
        + inbox: `https://api2.frontapp.com/channels/cha_55c8c149/inbox` (string, required) - URL of the inbox to which the channel is sending messages.
        + owner: `https://api2.frontapp.com/teams/tim_55c8c149` (string, required) - URL of the team of teammate of the channel
+ id: `cha_55c8c149` (string, required) - Unique identifier for the channel.
+ address: `team@planet-express.com` (string, required) - Address receiving the messages.
+ type (enum[string], required) - Type of the channel.
    + Members
        + `smtp`
        + `imap`
        + `twilio`
        + `twitter`
        + `facebook`
        + `smooch`
        + `intercom`
        + `truly`
        + `custom`
+ send_as: `team@planet-express.com` (string, optional) - Address which appears as the sender for messages sent from Front.
+ settings (object, required)
+ is_private: `false` (boolean, required) - Whether or not the channel is individual

## Channel settings

+ settings (object, required)
  + webhook_url: `http://example.com` (string, optional) - `custom` type only. URL to which will be sent the replies of a custom message.
  + reply_mode: `unsupported` (enum, optional) - How the channel can be used to reply to a message.
  + compose_mode: `normal` (enum, optional) - Grants ability to compose new messages from this channel (`normal`) or prevents composing new messages (`unsupported`). Can be one of: `normal` or `unsupported`. (Default: `unsupported`)
  + contact_type: `email` (enum, optional) - Contact type the channel uses. It can only be set on channel creation. Can be one of: `custom`, `email` or `phone`. (Default: `custom`)

## Channel to create

+ name: `My channel` (string, optional) - Name of the channel.
+ type (enum[string], required) - Type of the channel.
    + Members
        + `custom`
+ Include Channel settings

## Channel created

+ id: `cha_55c8c149` (string, required) - Unique identifier for the channel.
+ Include Channel to create
+ address: `dw0a0b7aeg36cb56` - Address receiving the messages.
+ sendAs: `dw0a0b7aeg36cb56` - Address which appears as the sender for messages sent from Front.
+ Include Channel settings

## Channel to update
+ name: `My channel` (string, optional) - Name of the channel.
+ settings (object, optional) - Settings to replace.
