## Contact

<!-- include(../includes/links_attribute.apib) -->
    + self: `https://api2.frontapp.com/contacts/crd_55c8c149` (string, required) - URL of the contact
    + related (object, required)
        + notes: `https://api2.frontapp.com/contacts/crd_55c8c149/notes` (string, required) - URL to list the notes associated to the contact
        + conversations: `https://api2.frontapp.com/contacts/crd_55c8c149/conversations` (string, required) - URL to list the URL associated to the contact
        + owner: `https://api2.frontapp.com/teams/tim_55c8c149` (string, required) - URL of the team or teammate of the contact
+ id: `crd_55c8c149` (string, required) - Unique identifier of the contact
+ name: `Calculon` (string, required) - Contact name
+ description: `#vip #robot #RIP` (string, required) - Contact description
+ avatar_url: `http://example.com/calculon.jpg` (string, required) - URL of the contact's avatar
+ is_spammer: `true` (boolean, required) - Whether or not the contact is a spammer
+ links (array[string], required) - A set of URL associated to the contact
    + `http://example.com`
+ handles (array[Contact handle], required) - List of the handles and sources with which the contact is reachable.
+ groups (array[Contact group], required) - List of the groups the contact belongs to.
+ updated_at (number) - Timestamp of the last update
+ custom_fields (object, required)
    + job title: `engineer` (string, required)
    + custom field name: `your value` (string, required)
+ is_private: `false` (boolean, required) - Whether or not the contact is individual


## Contact to update

+ name: `Calculon` (string, optional) - Contact name
+ description: `#vip #robot #RIP` (string, optional) - Contact description
+ avatar (string, optional) - Binary data of the image to use as the contact avatar. Available only for [multipart request](#send-multipart-request).
+ is_spammer: `true` (boolean, optional) - Whether or not the contact is marked as a spammer
+ links (array[string], optional) - List of all the links of the contact
    + `http://example.com`
+ group_names (array[string], optional) - List of all the group names the contact belongs to. It will automatically create missing groups.
    + `Customers`
+ custom_fields (object, optional) - Custom field attributes for this contact. Leave empty if you do not wish to update the attributes. Not sending existing attributes will automatically remove them.
    + job title: `engineer` (string, required) - A custom field name defined in your company custom fields
    + custom field name: `your value` (string, required) - A custom field name defined in your company custom fields

## Contact to create

+ Include Contact to update
* handles (array[Contact handle], required) - List of the contact handles

## Contact handle

+ handle: `@calculon` (string, required) - Handle used to reach the contact. Can be an email address, a twitter, handle, a phone number, ...
+ source (enum[string], required) - Can be 'twitter', 'email' or 'phone'.
    + Members
        + `twitter`
        + `email`
        + `phone`
        + `facebook`

## Contact handle to delete

+ Include Contact handle
+ force (boolean, optional) - Force the deletetion of the contact if the handle is the last one (Defaults to `false`)

## Contact note

+ author (Teammate, required) - Teammate who wrote the note
+ body: `Calculon is a celebrated actor` (string, required) - Content of the note
+ created_at: `1453770984.123` (number, required) - Date at which the note have been created

## Contact note to create

+ author_id: `alt:email:leela@planet-express.com` (string, required) - ID of the teammate creating the note
+ body: `Calculon is a celebrated actor` (string, required) - Content of the note

## Contact group

<!-- include(../includes/links_attribute.apib) -->
    + self: `https://api2.frontapp.com/contacts/grp_55c8c149` (string, required) - URL of the group
    + related (object, required)
        + contacts: `https://api2.frontapp.com/contact_groups/grp_55c8c149/contacts` (string, required) - URL to list of contacts in the group
        + owner: `https://api2.frontapp.com/teams/tim_55c8c149` (string, required) - URL of the team or teammate of the contact group
+ id: `grp_55c8c149` (string, required) - Unique identifier of the group
+ Include Contact group to create
+ is_private: `false` (boolean, required) - Whether or not the contact is individual

## Contact group to create

+ name: `Customers` (string, required) - Name of the group

## Contact IDs

+ contact_ids (array[string], required) - List of ids or aliases of the contacts to add in the requested group
    + `crd_55c8c149`
    + `alt:email:calculon@momsbot.com`
