## Message

<!-- include(../includes/links_attribute.apib) -->
    + self: `https://api2.frontapp.com/messages/msg_55c8c149` (string, required) - URL of the message
    + related (object, required)
        + conversation: `https://api2.frontapp.com/conversations/cnv_55c8c149` (string, required) - URL of the parent conversation
        + message_replied_to: `https://api2.frontapp.com/messages/msg_1ab23cd4` (string, optional) - URL of the message which have been replied to
+ id: `msg_55c8c149` (string, required) - Unique identifier of the message
+ type (enum[string], required) - Type of the message
    + Members
        + `email`
        + `tweet`
        + `sms`
        + `smooch`
        + `facebook`
        + `intercom`
        + `truly-call`
        + `custom`
+ is_inbound: `true` (boolean, required) - Whether or not the message has been received or sent
+ is_draft: `false` (boolean, required) - Whether or not the message is a draft
+ error_type (string, optional) - Type of the error when the draft failed to be sent
+ created_at: `1453770984.123` (number, required) - Date at which the message as been sent or received
+ blurb: `Anything less than immortality is a...` (string, required) - Preview of the message body
+ author (Teammate, optional) - In case of a message sent from Front by a teammate, it will include the teammate who sent it
+ recipients (array[Recipient], required) - List of the message recipients
+ body: `Anything less than immortality is a complete waste of time.` (string, required) - Body of the message
+ text: `Anything less than immortality is a complete waste of time.` (string, optional) - Text version of the body for email messages
+ attachments (array[Attachment], required) - List of files attached to the message
+ metadata (object, optional) - Optional metadata about the message
    + intercom_url (string, optional) - For `intercom` messages only. URL of the Intercom conversation the message is comming from.
    + duration (number, optional) - For `truly-call` messages only. Length of the call in seconds.
    + have_been_answered (boolean, optional) - For `truly-call` messages only. Whether or not the call have been answered.
    + twitter_url (string, optional) - For `tweet` messages only. URL of the tweet.
    + is_retweet (boolean, optional) - For `tweet` messages only. Whether or not the tweet is a retweet.
    + have_been_retweeted (boolean, optional) - For `tweet` messages only. Whether or not the tweet have been retweeted.
    + have_been_favorited (boolean, optional) - For `tweet` messages only. Whether or not the tweet have been favorited.
    + thread_ref (string, optional) - For `custom` messages only. Custom reference which is used to thread messages.
    + headers (object, optional) - For `custom` messages only. Custom object holding internal information.

## Outbound message

+ author_id: `alt:email:leela@planet-exress.com` (string, optional) - ID of the teammate on behalf of whom the answer is sent
+ sender_name: `Leela` (string, optional) - Name used for the sender info of the message
+ subject: `Good news everyone!` (string, optional) - Subject of the message for email message
+ body: `Why is Zoidberg the only one still alone?` (string, required) - Body of the message
+ text: `Why is Zoidberg the only one still alone?` (string, optional) - Text version of the body for messages with non-text body
+ attachments (array[], optional) - Binary data of the attached files. Available only for [multipart request](#send-multipart-request).
+ options (object, optional) - Sending options
    + tags (array[string], optional) - List of tag names to add to the conversation (unknown tags will automatically be created)
    + archive: `true` (boolean, optional) - Archive the conversation right when sending the message
        + Default: `true`

## Draft
+ Include Message
+ is_inbound: `false` (boolean, required)
+ is_draft: `true` (boolean, required)
+ blurb: `Why is Zoidberg the only one still...` (string, required)
+ body: `Why is Zoidberg the only one still alone?` (string, required)
+ text: `Why is Zoidberg the only one still alone?` (string, optional)
+ attachments (array[], optional)

## Outbound new message

+ Include Outbound message
+ to: `calculon@momsbot.com` (array[string], required) - List of the recipient handles who will receive this message
+ cc (array[string], optional) - List of the recipient handles who will receive a copy of this message
+ bcc (array[string], optional) - List of the recipient handles who will receive a blind copy of this message

## Outbound reply

+ Include Outbound message
+ `channel_id`: `cha_55c8c149` (string, optional) - Channel through which to send the message. Defaults to the original conversation channel. For imported messages or messages received on multiple channels, you **MUST** specify a channel ID.
+ to (array[string], optional) - List of the recipient handles who will receive this message. By default it will use the recipients of the last received message.
+ cc (array[string], optional) - List of the recipient handles who will receive a copy of this message. By default it will use the cc'ed recipients of the last received message.
+ bcc (array[string], optional) - List of the recipient handles who will receive a blind copy of this message

## Custom message

+ sender (object, required) - Data of the sender
    + contact_id (string, optional) - ID of the contact in Front corresponding to the sender
    + name: `hermes` (string, optional) - Name of the sender
    + handle: `hermes_123` (string, required) - Handle of the sender. It can be any string used to uniquely identify the sender
+ subject: `Question` (string, optional) - Subject of the message
+ body: `Didn't we used to be a delivery company?` (string, required) - Body of the message
+ body_format: `markdown` (enum[string], optional, default) - Format of the message body.
     + `html`
     + `markdown`
+ attachments (array[], optional) - Binary data of the attached files. Available only for [multipart request](#send-multipart-request).
+ metadata (object, optional)
    + thread_ref (string, optional) - Custom reference which will be used to thread messages. If you omit this field, we'll thread by sender instead
    + headers (object, optional) - Custom object where any internal information can be stored

## Message to import

+ sender (object, required)
  + handle: `calculon@momsbot.com` (string, required) - Handle used to reach the contact. Can be an email address, a twitter, handle, a phone number, custom handle ...
  + name (string, optional) - Name of the contact.
  + author_id (string, optional) - ID of the teammate who is the author of the message. Ignored if the message is inbound.
+ to (array[string], required) - List of recipient handles who received the message.
+ cc (array[string], optional) - List of recipient handles who received a copy of the message.
+ bcc (array[string], optional) - List of the recipeient handles who received a blind copy of the message.
+ subject (string, optional) - Subject of the message.
+ body (string, required) - Body of the message.
+ body_format: `markdown` (enum[string], optional, default) - Format of the message body. Ignored if the message type is not `email`.
     + `html`
     + `markdown`
+ external_id (string, required) - External identifier of the message. Front won't import two messages with the same external ID.
+ created_at: `1453770984.123` (number, required) - Date at which the message as been sent or received.
+ type: `email` (enum[string], optional, default) - Type of the message to import.
     + `email`
     + `sms`
     + `intercom`
     + `custom`
+ assignee_id (string, optional) - ID of the teammate who will be assigned to the conversation.
+ tags (array[string], optional) - List of tag names to add to the conversation (unknown tags will automatically be created).
+ attachments (array[], optional) - Binary data of the attached files. Available only for [multipart request](#send-multipart-request).
+ metadata (object, required)
    + thread_ref (string, optional) - Custom reference which will be used to thread messages. If you omit this field, we'll thread by sender instead.
    + is_inbound: `true` (boolean, required) - Whether or not the message is received (inbound) or sent (outbound) by you.
    + is_archived: `true` (boolean, optional) - Whether or not the message should be directly archived once imported.
        + Default: `true`
    + should_skip_rules: `true` (boolean, optional) - Whether or not the rules should apply to this message.
        + Default: `true`

## Accepted message

+ message_uid: `3b1q41d8` (string, required) - UID of the message that will be created.
