
## ShiftIntervals

+ mon (ShiftInterval, optional) - Monday interval
+ tue (ShiftInterval, optional) - Tuesday interval
+ wed (ShiftInterval, optional) - Wednesday interval
+ thu (ShiftInterval, optional) - Thursday interval

# ShiftInterval

+ start: `09:00` (string, required) Start of the shift
+ end: `17:00` (string, required) End of the shift