## Tag

<!-- include(../includes/links_attribute.apib) -->
    + self: `https://api2.frontapp.com/tags/tag_55c8c149` (string, required) - URL of the tag
    + related (object, required)
        + conversations: `https://api2.frontapp.com/tags/tag_55c8c149/conversations` (string, required) - URL of the list of conversations tagged with this tag
        + owner: `https://api2.frontapp.com/teams/tim_55c8c149` (string, required) - URL of the team or teammate of the tag
        + parent_tag: `https://api2.frontapp.com/tags/tag_1ab23cd4` (string, required) - URL of the parent tag
+ id: `tag_55c8c149` (string, required) - Unique identifier of the tag
+ name: `Robots` (string, required) - Name of the tag
+ highlight: `blue` (enum, required) - Highlight color of the tag. Can be one of: `grey`, `pink`, `red`, `orange`, `yellow`, `green`, `blue`, `blue` or `purple`.
+ is_private: `false` (boolean, required) - Whether or not the tag is individual

## Tag to create

+ name: `Robots` (string, required) - Name of the tag to create.
+ highlight: `blue` (enum, optional) - Color to highlight the tag with. Can be one of: `grey`, `pink`, `red`, `orange`, `yellow`, `green`, `blue`, `blue` or `purple`.

## Tag to update
+ name: `Robots` (string, optional) - Name of the tag to create.
+ highlight: `blue` (string, optional) - Color to highlight the tag with. Can be one of: `grey`, `pink`, `red`, `orange`, `yellow`, `green`, `blue`, `blue` or `purple`.

