## Tag

+ id: `tag_55c8c149` (string, required) - Unique identifier of the tag
+ name: `Robots` (string, required) - Name of the tag
<!-- include(../includes/links_attribute.apib) -->
    + self: `https://api2.frontapp.com/tags/tag_55c8c149` (string, required) - URL of the tag
    + related (object, required)
        + conversations: `https://api2.frontapp.com/tags/tag_55c8c149/conversations` (string, required) - URL of the list of conversations tagged with this tag

## Tag to create

+ name: `Robots` (string, required) - Name of the tag to create
