## Channels [/channels/{channel_id}]

A channel is a resource which can send and receive messages.

For information on building your own channel type integration, see the [Channels API offering](/channels-api.html) for more info.

Here is the list of existing channel types:

| Type        | Description                                                                                |
|-------------|--------------------------------------------------------------------------------------------|
| `smtp`      | For emails managed via SMTP.                                                               |
| `imap`      | For emails managed via IMAP.                                                               |
| `twilio`    | Linked to a Twilio account.                                                                |
| `twitter`   | Linked to a Twitter account.                                                               |
| `facebook`  | Linked to a Facebook page.                                                                 |
| `smooch`    | Linked to a Smooch account.                                                                |
| `intercom`  | Linked to an Intercom account.                                                             |
| `truly`     | Linked to a truly account.                                                                 |
| `custom`    | For messages sent and received only through the API (cf [Custom inboxes](/channels-api.html)).|

+ Parameters
    + channel_id (string, required) - Id of the requested channel

+ Attributes (Channel)

### List channels [GET /channels]

Lists all the channels.

<aside class="notice">
You can list the channels of a specific teammate or team by using the endpoints <code>/teammates/{teammate_id}/channels</code> or <code>/teams/{team_id}/channels</code>.
</aside>

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../includes/links_attribute.apib) -->
            + self: `https://api2.frontapp.com/channels` (string, required)
        + _results (array[Channel], required) - List of channels

### Get a channel [GET]

Fetches the information of a channel. See [resource aliases](#resource-aliases) to fetch by address.

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes (Channel)

### Create an SMTP channel [POST /inboxes/{inbox_id}/channels]

Creates an SMTP channel linked to the requested inbox.

<aside class="notice">
As of today, you can only create an SMTP channel with the API.
</aside>

For `smtp` type channels, we will create an **unvalidated** SMTP channel.
* In the response body returned, `address` is the **forwarding address**.
* To complete the SMTP validation process, [add the forwarding address to your email provider's settings](https://help.frontapp.com/t/632v5z/switch-from-gmailo365-to-smtp-forwarding).

+ Parameters
    + inbox_id (string, required) - Id of the inbox into which the channel messages will go.

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Channel to create)

+ Response 201 (application/json)
    + Attributes (Channel created)

### Receive Message [POST /channels/{channel_id}/inbound_messages]

This endpoint is used in building your own channel type. See the [Channels API offering](/channels-api.html) for more info. When your system receives a message, this message can be sent to the Front channel by posting it to this endpoint.

+ Parameters
    + channel_id (string, required) - The id of the channel this message is sent to

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Incoming message)

+ Response 200 (application/json)
    + Attributes (Inbound message received)

### Import Sent Message [POST /channels/{channel_id}/outbound_messages]

This endpoint is used in building your own channel type. See the [Channels API offering](/channels-api.html) for more info. This endpoint enables messages sent directly from an external service to reflect as a sent message in Front as well.

+ Parameters
    + channel_id (string, required) - The id of the channel this message is sent to

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Import outbound message)

+ Response 200 (application/json)
    + Attributes (Outbound message received)