## Exports [/exports/{export_id}]

Front can generate exports of your data for a specific timeframe and/or specific inboxes, teammates or tags.

Since an export takes some time to process, it has a `status` which can be either:

* `pending` when the export is still generating
* `done` once the export has been generated
* `failed` in case the generation failed

Once the export has been generated, you can download it with its `url`.

+ Parameters
    + export_id (string, required) - ID of the requested export

+ Attributes (Export)

### List exports [GET /exports{?page}]

Lists all the exports generated in your company.

+ Parameters
    <!-- include(../includes/pagination_parameter.apib) -->

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../includes/pagination_attribute.apib) -->
        <!-- include(../includes/links_attribute.apib) -->
            + self: `https://api2.frontapp.com/exports` (string, required)
        + _results (array[Export], required) - List of the exports created

### Get export [GET]

Fetches the information of an export.

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes (Export)

### Create export [POST /exports]

Requests the creation of a new export

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Export to create)

+ Response 201 (application/json)
    + Attributes (Export)
