## Exports [/exports/{export_id}]

Front can generate exports of your data for a specific timeframe and/or specific inboxes, teammates or tags.

Since an export takes some time to process, it has a `status` which can be either:

* `pending` when the export is still generating
* `done` once the export has been generated
* `failed` in case the generation failed

Once the export has been generated, you can download it with its `url`.

### Format

Exports are formatted as a [CSV](https://en.wikipedia.org/wiki/Comma-separated_values) files. The export will contain 1 line per message received in the given time period.

**If a message appears in multiple inboxes, it will appear once for each inbox**.

Below is table of the field names & descriptions that will be included in the export.

| Name                | Desctiption                                                                                                                                       |
|---------------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| Message ID          | Internal Front ID of the message                                                                                                                  |
| Conversation ID     | Internal Front ID of the entire conversation                                                                                                      |
| Segment             | Segment of the conversation                                                                                                                       |
| Direction           | Either `Inbound` or `Outbound`                                                                                                                    |
| Status              | Status of the conversation: `unassigned`, `assigned`, `archived`, or `trashed`                                                                    |
| Inbox               | Name of the inbox where the message was initially sent. If the message appeared in multiple inboxes, it will appear multiple times.               |
| Message Date        | `YYYY-MM-DD HH:mm:ss` format, in the requested timezone                                                                                           |
| Reaction time       | Time (in seconds) taken to respond or reassign a conversation                                                                                     |
| Resolution time     | Total duration (in seconds) that a contact was kept waiting for a reply from the team during a conversation segment                               |
| Response time       | Duration (in seconds) between an inbound message and the next outbound message in the same conversation                                           |
| Assignee            | Username of the assignee, if any                                                                                                                  |
| Author              | Username of the teammate who replied to the email                                                                                                 |
| Contact name        | Contact's first & last name                                                                                                                       |
| Contact handle      | Contact's email address, twitter handle, or phone number - depending on the source of the message                                                 |
| To                  | Email address of the recipient                                                                                                                    |
| Cc                  | Email address of those CC'ed on the email                                                                                                         |
| Bcc                 | Email address of those BCC'ed on the email                                                                                                        |
| Extract             | Sample of the message                                                                                                                             |
| Tags                | Tags attached to the conversation                                                                                                                 |
| Message API ID      | Public Front ID of the message                                                                                                                    |
| Conversation API ID | Public Front ID of the conversation                                                                                                               |

**Timezone**

All dates in the the export are presented in the same timezone. If the export was requested from the app (by clicking on "Request Export"), it will be in the timezone of the user. If the export is requested with the API, the timezone can be manually defined (or defaults to UTC).

**Response time**

Response time is always calculated from the point of view of a customer: how did it take for your company to reply?

Most of the time, the response time is the difference between an inbound message from a customer and the next reply from your team.

If your team replies several times to the same message, the response time is the time since the previous reply.

**Assignments and Handle time**

Most of the time, only one discussion happens within a conversation. That is: a customer will open a conversation to ask a specific thing and if they want to ask another one, they will open a new discussion.

However, this is not always the case:

* A customer might decide to reply to an existing conversation even if they are asking for something new.
* Several teammates might write in one conversation.

Because of this, Front will compute a **handle time** to the last message if:

* the conversation is reassigned to a different teammate.
* the conversation is inactive for **4 days**.

+ Parameters
    + export_id (string, required) - ID of the requested export

+ Attributes (Export)

### List exports [GET /exports{?page_token,limit}]

Lists all the exports generated in your company.

+ Parameters
    <!-- include(../includes/pagination_parameter.apib) -->

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../includes/pagination_attribute.apib) -->
        <!-- include(../includes/links_attribute.apib) -->
            + self: `https://api2.frontapp.com/exports` (string, required)
        + _results (array[Export], required) - List of the exports created

### Get export [GET]

Fetches the information of an export.

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes (Export)

### Create export [POST /exports]

Create a new export in the default team.

<aside class="notice">
You can create a new export in a specific team by using the endpoint <code>/teams/{team_id}/exports</code>.
</aside>

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Export to create)

+ Response 201 (application/json)
    + Attributes (Export)
