## Messages [/messages/{message_id}]

A message is a resource which can be either received or sent via an inbox. Messages are grouped by conversations.

A message can be either inbound (received) or outbound (sent). You can know if a message has been received or sent thanks to the boolean `is_inbound`.

Each message has a type depending on the channel it has been sent with:

| Type name    | Description                          |
|--------------|--------------------------------------|
| `email`      | Email message                        |
| `tweet`      | Message from Twitter                 |
| `tweet_dm`   | Direct Message from Twitter          |
| `sms`        | SMS message                          |
| `smooch`     | Message from Smooch                  |
| `facebook`   | Message from Facebook                |
| `intercom`   | Message from Intercom                |
| `call`       | Phone call                           |
| `custom`     | [Custom message](/channels-api.html) |

<aside class="notice">
In order to comply with <a href="https://developer.twitter.com/en/developer-terms/policy#f-be-a-good-partner-to-twitter">Twitter's API Terms & Conditions</a>, Twitter content is not distributed through Front API.<br>
The fields <code>blurb</code>, <code>body</code>, <code>text</code> as well as recipients' <code>handle</code> are replaced by the string <code>[REDACTED]</code> for messages of type <code>tweet</code> or <code>tweet_dm</code> only.
<br><br>
For those messages, the payload includes the field <code>metadata.external_id</code> containing the ID of the original Tweet or Twitter Direct Message that can be used to fetch its content from the Twitter API directly.
</aside>

### Opening a message in Front

To open a message in Front you need to open the URL `https://app.frontapp.com/open/{message_id}`.

+ Parameters
    + message_id (string, required) - Id of the requested message

+ Attributes (Message)

### Get message [GET]

Fetches the information of a message.

<aside class="notice">
You can request the source of a message by setting the <code>Accept</code> header to <code>"text/plain"</code>.<br />
Fetching the source of a message is available for email messages only.
</aside>

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes (Message)

### Send new message [POST /channels/{channel_id}/messages]

Sends a new message from a channel. It will create a new conversation.

If you want to send a new message with attached files, please check [how to send multipart request](#send-multipart-request).

+ Parameters
    + channel_id (string, required) - Id or address of the channel from which to send the message

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Outbound new message)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Draft)

### Send reply [POST /conversations/{conversation_id}/messages]

Replies to a conversation by sending a message and appending it to the conversation.

If you want to send a reply with attached files, please check [how to send multipart request](#send-multipart-request).

+ Parameters
    + conversation_id (string, required) - Id of the conversation

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Outbound reply)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Draft)

### Import message [POST /inboxes/{inbox_id}/imported_messages]

Appends a new message into an inbox.

If you want to import a message with attached files, please check [how to send multipart request](#send-multipart-request).

<aside class="notice">
Importing a message in Front is done asynchronously. <br>
The endpoint will only validate the payload and will return a <code>message_uid</code> that can be used as an alias for the message ID (<code>alt:uid:{message_uid}</code>.
<br><br>
We guarantee that the UID will refer to a message but we don't guarantee that the message already exists. The API might respond with a 404 error code if trying to use the UID before the message is effectively created.
</aside>

<aside class="warning">
Imported messages will <strong>NOT</strong> be linked to any channel until a reply is sent. When replying to a conversation with no channels, you <strong>MUST</strong> choose from which channel to send the message.
</aside>

+ Parameters
    + inbox_id (string, required) - Id of the inbox into which the message should be append.

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Message to import)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Accepted message)
