## Messages [/messages/{message_id}]

A message is a resource which can be either received or sent via an inbox. Messages are grouped by conversations.

A message can be either inbound (received) or outbound (sent). You can know if a message has been received or sent thanks to the boolean `is_inbound`.

Each message has a type depending on the channel it has been sent with:

| Type name    | Description                        |
|--------------|------------------------------------|
| `email`      | Email message                      |
| `tweet`      | Message from Twitter               |
| `sms`        | SMS message                        |
| `smooch`     | Message from Smooch                |
| `facebook`   | Message from Facebook              |
| `intercom`   | Message from Intercom              |
| `call`       | Phone call                         |
| `custom`     | [Custom message](#custom-channels) |

### Opening a message in Front

To open a message in Front you need to open the URL `https://app.frontapp.com/open/{message_id}`.

<aside class="notice">
Creating messages in Front is done asynchronously: the endpoint will only validate that the message can be processed.<br>
Because of that, the response body does not include a conversation or message ID but includes aliases for them: a <code>conversation_reference</code> that can be used in place of the conversation ID, and a <code>message_uid</code> that can be used in place of the message ID.<br>

We guarantee that an alias will refer to its conversation or message but we don't guarantee that the object already exists when you receive its alias. So the API might respond with a 404 error code if trying to use a reference or UID before the conversation or message exists.
</aside>

+ Parameters
    + message_id (string, required) - Id of the requested message

+ Attributes (Message)

### Get message [GET]

Fetches the information of a message.

<aside class="notice">
You can use the message UID as an alias for its ID. The UID to use can be found in the response of the endpoints to create messages.<br>
A message ID alias follows the pattern <code>alt:uid:{message_uid}</code>.
</aside>

<aside class="notice">
You can request the source of a message by setting the <code>Accept</code> header to <code>"text/plain"</code>.<br />
Fetching the source of a message is available for email messages only.
</aside>

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes (Message)

### Send new message [POST /channels/{channel_id}/messages]

Sends a new message from a channel. It will create a new conversation.

If you want to send a new message with attached files, please check [how to send multipart request](#send-multipart-request).

+ Parameters
    + channel_id (string, required) - Id or address of the channel from which to send the message

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Outbound new message)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Accepted message)

### Send reply [POST /conversations/{conversation_id}/messages]

Replies to a conversation by sending a message and appending it to the conversation.

If you want to send a reply with attached files, please check [how to send multipart request](#send-multipart-request).

+ Parameters
    + conversation_id (string, required) - Id of the conversation

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Outbound reply)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Accepted reply)

### Receive custom message [POST /channels/{channel_id}/incoming_messages]

Receives a custom message in Front. This endpoint is available for [custom channels](#custom-channels) **ONLY**.

If you want to receive a custom message with attached files, please check [how to send multipart request](#send-multipart-request).

+ Parameters
    + channel_id (string, required) - Id of the requested custom channel

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Custom message)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Accepted message)

### Import message [POST /inboxes/{inbox_id}/imported_messages]

Appends a new message into an inbox.

If you want to import a message with attached files, please check [how to send multipart request](#send-multipart-request).

<aside class="warning">
Imported messages will <strong>NOT</strong> be linked to any channel until a reply is sent. When replying to a conversation with no channels, you <strong>MUST</strong> choose from which channel to send the message.
</aside>

+ Parameters
    + inbox_id (string, required) - Id of the inbox into which the message should be append.

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Message to import)

<!-- include(../includes/accepted_response.apib) -->
    + Attributes (Accepted message)
