## Tags [/tags/{tag_id}]

A tag is a label that can be used to classify conversations.

A tag has an optional `highlight` field which represents the color to highlight the tag with in Front.  
Supported values for highlight colors are:

| Color Preview                                      | Color value  |
|----------------------------------------------------|--------------|
| ![#](https://placehold.it/15/9b9c9e/000000?text=+) | `grey`       |
| ![#](https://placehold.it/15/ff338f/000000?text=+) | `pink`       |
| ![#](https://placehold.it/15/ff4433/000000?text=+) | `red`        |
| ![#](https://placehold.it/15/ff901a/000000?text=+) | `orange`     |
| ![#](https://placehold.it/15/facc25/000000?text=+) | `yellow`     |
| ![#](https://placehold.it/15/14cc52/000000?text=+) | `green`      |
| ![#](https://placehold.it/15/2bd5ff/000000?text=+) | `teal`       |
| ![#](https://placehold.it/15/367fee/000000?text=+) | `blue`       |
| ![#](https://placehold.it/15/a238ff/000000?text=+) | `purple`     |

Tags can have a parent - child relationship with other tags.

+ Parameters
    + tag_id (string, required) - ID of the requested tag

+ Attributes (Tag)

### List tags [GET /tags]

Lists all the tags.

<aside class="notice">
You can list the tags of a specific teammate or team by using the endpoints <code>/teammates/{teammate_id}/tags</code> or <code>/teams/{team_id}/tags</code>.
</aside>

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../includes/links_attribute.apib) -->
            + self: `https://api2.frontapp.com/tags` (string, required)
        + _results (array[Tag], required) - List of the tags available in your company

### Create tag [POST /tags]

Creates a new tag in the default team.

<aside class="notice">
You can create a tag for a specific teammate or team by using the endpoints <code>/teammates/{teammate_id}/tags</code> or <code>/teams/{team_id}/tags</code>.
<br>
You can create a child tag for a specific tag by using the endpoint <code>/tags/{tag_id}/children</code>.
</aside>

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Tag to create)

+ Response 201 (application/json)
    + Attributes (Tag)

### Get tag [GET]

Fetches the information of a tag.

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes (Tag)

### Update tag [PATCH]

Updates a tag.

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Tag to update)

+ Response 204

### Delete tag [DELETE]

Deletes a tag.

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->

+ Response 204 (application/json)

### List tag conversations [GET /tags/{tag_id}/conversations{?q,page_token,limit}]

Lists all the conversations tagged with a specific tag.

+ Parameters
    + tag_id (string, required) - ID of the requested tag
    <!-- include(../includes/query_parameter.apib) -->
    <!-- include(../includes/pagination_parameter.apib) -->

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../includes/pagination_attribute.apib) -->
        <!-- include(../includes/links_attribute.apib) -->
            + self: `https://api2.frontapp.com/tags/tag_55c8c149/conversations` (string, required)
        + _results (array[Conversation], required) - List of the tag's conversations

### List tag children [GET /tags/{tag_id}/children]

Lists the first level of children of the requested tag.

+ Parameters
    + tag_id (string, required) - ID of the requested tag

+ Request
    <!-- include(../includes/request_header.apib) -->

+ Response 200 (application/json)
    + Attributes
        <!-- include(../includes/links_attribute.apib) -->
            + self: `https://api2.frontapp.com/tags/tag_55c8c149/children` (string, required)
        + _results (array[Tag], required) - List of the child tags

### Create child tag [POST /tags/{tag_id}/children]

Creates a new child tag for the given tag.

+ Parameters
    + tag_id (string, required) - ID of the requested tag

+ Request (application/json)
    <!-- include(../includes/request_header.apib) -->
    + Attributes (Tag to create)

+ Response 201 (application/json)
    + Attributes (Tag)
