FORMAT: 1A
HOST: https://api2.frontapp.com/

# Front

# Group Teammates
:[Teammate related endpoints](endpoints/teammates.apib)

# Group Inboxes
:[Inbox related endpoints](endpoints/inboxes.apib)

# Group Channels
:[Channel related endpoints](endpoints/channels.apib)

# Group Conversations
:[Conversation related endpoints](endpoints/conversations.apib)

# Group Messages
:[Message related endpoints](endpoints/messages.apib)

# Group Contacts
:[Contact related endpoints](endpoints/contacts.apib)

# Group Tags
:[Tag related endpoint](endpoints/tags.apib)

# Group Rules
:[Rule related endpoint](endpoints/rules.apib)

# Group Events
:[Event related endpoint](endpoints/events.apib)

# Group Analytics
:[Analytics related endpoint](endpoints/analytics.apib)

# Group Exports
:[Export related endpoint](endpoints/exports.apib)

# Data Structures
:[Teammate data structure](data_structures/teammate.apib)
:[Inbox data structure](data_structures/inbox.apib)
:[Conversation data structure](data_structures/conversation.apib)
:[Message data structure](data_structures/message.apib)
:[Recipient data structure](data_structures/recipient.apib)
:[Event data structure](data_structures/event.apib)
:[Comment data structure](data_structures/comment.apib)
:[Attachment data structure](data_structures/attachment.apib)
:[Contact data structure](data_structures/contact.apib)
:[Tag data structure](data_structures/tag.apib)
:[Rule data structure](data_structures/rule.apib)
:[Export data structure](data_structures/export.apib)
:[Analytics data structure](data_structures/analytics.apib)
:[Channel data structure](data_structures/channel.apib)
