FORMAT: 1A
HOST: https://api2.frontapp.com/

# Front

# Group Token identity
<!-- include(endpoints/identity.apib) -->

# Group Teams
<!-- include(endpoints/teams.apib) -->

# Group Teammates
<!-- include(endpoints/teammates.apib) -->

# Group Inboxes
<!-- include(endpoints/inboxes.apib) -->

# Group Channels
<!-- include(endpoints/channels.apib) -->

# Group Conversations
<!-- include(endpoints/conversations.apib) -->

# Group Custom fields
<!-- include(endpoints/custom_fields.apib) -->

# Group Messages
<!-- include(endpoints/messages.apib) -->

# Group Contacts
<!-- include(endpoints/contacts.apib) -->

# Group Tags
<!-- include(endpoints/tags.apib) -->

# Group Topics
<!-- include(endpoints/topics.apib) -->

# Group Rules
<!-- include(endpoints/rules.apib) -->

# Group Events
<!-- include(endpoints/events.apib) -->

# Group Analytics
<!-- include(endpoints/analytics.apib) -->

# Group Exports
<!-- include(endpoints/exports.apib) -->

# Group Responses
<!-- include(endpoints/responses.apib) -->

# Data Structures
<!-- include(data_structures/teammate.apib) -->
<!-- include(data_structures/inbox.apib) -->
<!-- include(data_structures/conversation.apib) -->
<!-- include(data_structures/message.apib) -->
<!-- include(data_structures/recipient.apib) -->
<!-- include(data_structures/event.apib) -->
<!-- include(data_structures/comment.apib) -->
<!-- include(data_structures/attachment.apib) -->
<!-- include(data_structures/contact.apib) -->
<!-- include(data_structures/tag.apib) -->
<!-- include(data_structures/rule.apib) -->
<!-- include(data_structures/export.apib) -->
<!-- include(data_structures/analytics.apib) -->
<!-- include(data_structures/channel.apib) -->
<!-- include(data_structures/topic.apib) -->
<!-- include(data_structures/custom_field.apib) -->
<!-- include(data_structures/team.apib) -->
<!-- include(data_structures/response.apib) -->