+ _pagination (object, required) - Pagination object
    + limit (number) - The maximum number of resources listed per page
    + page (number) - The page number for the current page
    + prev (string, optional) - Link to the previous page
    + next (string, optional) - Link to the next page